Добавляет Главную страницу Седоны
htmlacademy-htmlcss/1984449-sedona-33 pull request #2
Opened 2022-01-22 15:43 UTC by Moonfaction

2022-01-23 13:04 UTC, Dima-Dim requested changes
Для того чтобы не совершать ошибки в связи с тем, что вам ещё что-то не рассказали на лайве или не дали в текстовых материалах нужно выполнять и отправлять на проверку только то, что указано в домашнем задании.
В текущем задании сказано: «Нужен только HTML-код, стили делать не нужно.». Т.е. добавлять в проект изображения на этом этапе не нужно.
Если есть свободное время, всегда можно перечитать критерии. Например, https://up.htmlacademy.ru/htmlcss/33/criteries#PROJ-03, в котором сказано «Файлы и папки должны быть записаны строчными буквами без пробелов между словами.».

Пожалуйста, больше внимательности, в том числе к текстовым материалам.

2022-01-23 13:04 UTC, Dima-Dim commented on index.html
> +    <h2 class="visually-hidden">Welcome to the gorgeous</h2>
Не нужно использовать заголовки без необходимости
https://up.htmlacademy.ru/htmlcss/33/module/2/item/16

2022-01-23 13:04 UTC, Dima-Dim commented on index.html
> +            <img class="adfantages-icon" src="./images/icon-2.svg" alt="Бургер">
https://up.htmlacademy.ru/htmlcss/33/module/2/item/19

2022-01-23 13:04 UTC, Dima-Dim commented on index.html
> +          <p>
https://up.htmlacademy.ru/htmlcss/33/module/2/item/8

2022-01-23 13:04 UTC, Dima-Dim commented on index.html
> +        <button>ПОИСК ГОСТИНИЦЫ В седоне</button>
Не нужно пытаться стилизовать текст в разметке, пишем слова как в обычных предложениях.

2022-01-24 15:45 UTC, Dima-Dim requested changes

2022-01-24 15:45 UTC, Dima-Dim commented on index.html
> +    <p> class="visually-hidden">Welcome to the gorgeous</p>
Хорошо. А для чего нам скрытые абзацы?

2022-01-24 15:45 UTC, Dima-Dim commented on index.html
> +        <button>ПОИСК ГОСТИНИЦЫ В седоне</button>
Не поправлено?

2022-01-24 21:28 UTC, Moonfaction commented on index.html
> +        <button>ПОИСК ГОСТИНИЦЫ В седоне</button>
Я просто копировал текст с макета

2022-01-24 21:30 UTC, Moonfaction commented on index.html
> +          <p>
Я проверил всё на валидаторе, он не показал ошибок

2022-01-25 05:30 UTC, Dima-Dim commented on index.html
> +        <button>ПОИСК ГОСТИНИЦЫ В седоне</button>
Это не правильный подход. Для того чтобы такого случайно не повторить, возьми себе за правило ничего просто так не копировать в проект :) а добавлять только осмысленные элементы, с пониманием того, что это за элементы, для чего они нужны и почему они именно такие.

2022-01-25 12:15 UTC, Dima-Dim approved these changes

2022-01-25 12:15 UTC, merged